-- New accounts wait outside all tenant data until they request access with an
-- owner-controlled workspace code and that workspace's owner approves them.

create table if not exists public.questdeck_workspace_join_codes (
  workspace_id text primary key references public.questdeck_workspaces(id) on delete cascade,
  join_code uuid not null unique default gen_random_uuid(),
  created_at timestamptz not null default now(),
  rotated_at timestamptz not null default now()
);

create table if not exists public.questdeck_membership_requests (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  email text not null,
  display_name text not null default '',
  target_workspace_id text not null references public.questdeck_workspaces(id) on delete cascade,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Declined')),
  requested_at timestamptz not null default now(),
  resolved_at timestamptz,
  unique (auth_user_id, target_workspace_id)
);

insert into public.questdeck_workspace_join_codes (workspace_id)
select workspace.id from public.questdeck_workspaces workspace
on conflict (workspace_id) do nothing;

create or replace function public.create_questdeck_workspace_join_code()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.questdeck_workspace_join_codes (workspace_id)
  values (new.id)
  on conflict (workspace_id) do nothing;
  return new;
end
$$;

drop trigger if exists questdeck_workspace_join_code_trigger on public.questdeck_workspaces;
create trigger questdeck_workspace_join_code_trigger
after insert on public.questdeck_workspaces
for each row execute function public.create_questdeck_workspace_join_code();

create index if not exists questdeck_membership_requests_workspace_status_idx
  on public.questdeck_membership_requests (target_workspace_id, status, requested_at);
create index if not exists questdeck_membership_requests_user_idx
  on public.questdeck_membership_requests (auth_user_id, status);

alter table public.questdeck_workspace_join_codes enable row level security;
alter table public.questdeck_membership_requests enable row level security;

revoke all on public.questdeck_workspace_join_codes from anon, authenticated;
revoke all on public.questdeck_membership_requests from anon, authenticated;
