-- Give every Questdeck workspace a real access boundary.
-- Existing production data remains in the oldest active workspace so the
-- migration is lossless, while owners retain access to every workspace.

create table if not exists public.questdeck_workspace_memberships (
  id bigint generated by default as identity primary key,
  workspace_id text not null references public.questdeck_workspaces(id) on delete cascade,
  member_id bigint not null references public.questdeck_members(id) on delete cascade,
  role text not null default 'Member' check (role in ('Owner', 'Admin', 'Team Leader', 'Member', 'Guest')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, member_id)
);

create index if not exists questdeck_workspace_memberships_member_idx
  on public.questdeck_workspace_memberships (member_id, workspace_id);

alter table public.questdeck_role_permissions
  drop constraint if exists questdeck_role_permissions_role_check;
alter table public.questdeck_role_permissions
  add constraint questdeck_role_permissions_role_check
  check (role in ('Owner', 'Admin', 'Team Leader', 'Member', 'Guest'));

insert into public.questdeck_role_permissions (
  role, view_projects, edit_cards, manage_members, workspace_settings, billing_security
)
values ('Team Leader', true, true, false, true, false)
on conflict (role) do update set
  view_projects = excluded.view_projects,
  edit_cards = excluded.edit_cards,
  manage_members = excluded.manage_members,
  workspace_settings = excluded.workspace_settings,
  billing_security = excluded.billing_security;

do $$
declare
  primary_workspace text;
begin
  select id into primary_workspace
  from public.questdeck_workspaces
  order by (status::text = 'Active') desc, created_at asc, id asc
  limit 1;

  if primary_workspace is null then
    insert into public.questdeck_workspaces (id, name, initials, member_count, status)
    values ('workspace', 'Workspace', 'W', 1, 'Active')
    returning id into primary_workspace;
  end if;

  insert into public.questdeck_workspace_memberships (workspace_id, member_id, role)
  select workspace.id, member.id, 'Owner'
  from public.questdeck_workspaces workspace
  cross join public.questdeck_members member
  where member.role::text = 'Owner'
  on conflict (workspace_id, member_id) do update set role = 'Owner', updated_at = now();

  insert into public.questdeck_workspace_memberships (workspace_id, member_id, role)
  select primary_workspace, member.id,
    case when member.role::text in ('Owner', 'Admin', 'Team Leader', 'Member', 'Guest')
      then member.role::text else 'Member' end
  from public.questdeck_members member
  where member.role::text <> 'Owner'
  on conflict (workspace_id, member_id) do nothing;

  alter table public.questdeck_projects add column if not exists workspace_id text references public.questdeck_workspaces(id) on delete cascade;
  alter table public.questdeck_cards add column if not exists workspace_id text references public.questdeck_workspaces(id) on delete cascade;
  alter table public.questdeck_subtasks add column if not exists workspace_id text references public.questdeck_workspaces(id) on delete cascade;
  alter table public.questdeck_disciplines add column if not exists workspace_id text references public.questdeck_workspaces(id) on delete cascade;
  alter table public.questdeck_documents add column if not exists workspace_id text references public.questdeck_workspaces(id) on delete cascade;
  alter table public.questdeck_document_comments add column if not exists workspace_id text references public.questdeck_workspaces(id) on delete cascade;
  alter table public.questdeck_milestones add column if not exists workspace_id text references public.questdeck_workspaces(id) on delete cascade;
  alter table public.questdeck_activity_events add column if not exists workspace_id text references public.questdeck_workspaces(id) on delete cascade;
  alter table public.questdeck_notifications add column if not exists workspace_id text references public.questdeck_workspaces(id) on delete cascade;

  update public.questdeck_projects set workspace_id = primary_workspace where workspace_id is null;
  update public.questdeck_cards card set workspace_id = coalesce(project.workspace_id, primary_workspace)
    from public.questdeck_projects project where card.project_id = project.id and card.workspace_id is null;
  update public.questdeck_cards set workspace_id = primary_workspace where workspace_id is null;
  update public.questdeck_subtasks task set workspace_id = coalesce(card.workspace_id, primary_workspace)
    from public.questdeck_cards card where task.card_id = card.id and task.workspace_id is null;
  update public.questdeck_subtasks set workspace_id = primary_workspace where workspace_id is null;
  update public.questdeck_disciplines set workspace_id = primary_workspace where workspace_id is null;
  update public.questdeck_documents set workspace_id = primary_workspace where workspace_id is null;
  update public.questdeck_document_comments comment set workspace_id = coalesce(document.workspace_id, primary_workspace)
    from public.questdeck_documents document where comment.document_id = document.id and comment.workspace_id is null;
  update public.questdeck_document_comments set workspace_id = primary_workspace where workspace_id is null;
  update public.questdeck_milestones set workspace_id = primary_workspace where workspace_id is null;
  update public.questdeck_activity_events set workspace_id = primary_workspace where workspace_id is null;
  update public.questdeck_notifications set workspace_id = primary_workspace where workspace_id is null;

  alter table public.questdeck_projects alter column workspace_id set not null;
  alter table public.questdeck_cards alter column workspace_id set not null;
  alter table public.questdeck_subtasks alter column workspace_id set not null;
  alter table public.questdeck_disciplines alter column workspace_id set not null;
  alter table public.questdeck_documents alter column workspace_id set not null;
  alter table public.questdeck_document_comments alter column workspace_id set not null;
  alter table public.questdeck_milestones alter column workspace_id set not null;
  alter table public.questdeck_activity_events alter column workspace_id set not null;
  alter table public.questdeck_notifications alter column workspace_id set not null;
end
$$;

create index if not exists questdeck_projects_workspace_idx on public.questdeck_projects (workspace_id);
create index if not exists questdeck_cards_workspace_idx on public.questdeck_cards (workspace_id);
create index if not exists questdeck_subtasks_workspace_idx on public.questdeck_subtasks (workspace_id);
create index if not exists questdeck_disciplines_workspace_idx on public.questdeck_disciplines (workspace_id);
create index if not exists questdeck_documents_workspace_idx on public.questdeck_documents (workspace_id);
create index if not exists questdeck_milestones_workspace_idx on public.questdeck_milestones (workspace_id);
create index if not exists questdeck_activity_workspace_idx on public.questdeck_activity_events (workspace_id, created_at desc);
create index if not exists questdeck_notifications_workspace_idx on public.questdeck_notifications (workspace_id, recipient_email, created_at desc);

do $$
declare
  constraint_name text;
  target_table text;
begin
  foreach target_table in array array['questdeck_projects', 'questdeck_disciplines']
  loop
    for constraint_name in
      select constraint_record.conname
      from pg_constraint constraint_record
      join pg_attribute attribute_record
        on attribute_record.attrelid = constraint_record.conrelid
       and attribute_record.attnum = any(constraint_record.conkey)
      where constraint_record.conrelid = ('public.' || target_table)::regclass
        and constraint_record.contype = 'u'
      group by constraint_record.conname, constraint_record.conkey
      having count(*) = 1 and max(attribute_record.attname) = 'name'
    loop
      execute format('alter table public.%I drop constraint %I', target_table, constraint_name);
    end loop;
  end loop;
end
$$;

alter table public.questdeck_projects
  drop constraint if exists questdeck_projects_workspace_name_key;
alter table public.questdeck_projects
  add constraint questdeck_projects_workspace_name_key unique (workspace_id, name);
alter table public.questdeck_disciplines
  drop constraint if exists questdeck_disciplines_workspace_name_key;
alter table public.questdeck_disciplines
  add constraint questdeck_disciplines_workspace_name_key unique (workspace_id, name);

create or replace function public.questdeck_current_member_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id from public.questdeck_members
  where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    and status::text = 'Active'
  limit 1
$$;

create or replace function public.has_questdeck_workspace_access(target_workspace_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.questdeck_workspace_memberships membership
    where membership.workspace_id = target_workspace_id
      and membership.member_id = public.questdeck_current_member_id()
  )
$$;

create or replace function public.is_questdeck_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.questdeck_workspace_memberships membership
    where membership.member_id = public.questdeck_current_member_id()
      and membership.role = 'Owner'
  )
$$;

create or replace function public.is_questdeck_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.questdeck_current_member_id() is not null
    and exists (
      select 1 from public.questdeck_workspace_memberships membership
      where membership.member_id = public.questdeck_current_member_id()
    )
$$;

create or replace function public.can_edit_questdeck_workspace(target_workspace_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.questdeck_workspace_memberships membership
    join public.questdeck_role_permissions permissions on permissions.role::text = membership.role
    where membership.member_id = public.questdeck_current_member_id()
      and membership.workspace_id = target_workspace_id
      and permissions.edit_cards
  )
$$;

revoke all on function public.questdeck_current_member_id() from public;
revoke all on function public.has_questdeck_workspace_access(text) from public;
revoke all on function public.is_questdeck_owner() from public;
revoke all on function public.is_questdeck_member() from public;
revoke all on function public.can_edit_questdeck_workspace(text) from public;
grant execute on function public.questdeck_current_member_id() to authenticated;
grant execute on function public.has_questdeck_workspace_access(text) to authenticated;
grant execute on function public.is_questdeck_owner() to authenticated;
grant execute on function public.is_questdeck_member() to authenticated;
grant execute on function public.can_edit_questdeck_workspace(text) to authenticated;

do $$
declare
  table_name text;
  policy record;
begin
  foreach table_name in array array[
    'questdeck_projects', 'questdeck_cards', 'questdeck_subtasks', 'questdeck_disciplines',
    'questdeck_documents', 'questdeck_document_comments', 'questdeck_milestones',
    'questdeck_activity_events', 'questdeck_notifications'
  ]
  loop
    for policy in select policyname from pg_policies where schemaname = 'public' and tablename = table_name
    loop
      execute format('drop policy %I on public.%I', policy.policyname, table_name);
    end loop;
    execute format(
      'create policy %I on public.%I for select to authenticated using (public.has_questdeck_workspace_access(workspace_id))',
      table_name || '_workspace_read', table_name
    );
  end loop;
end
$$;

do $$
declare policy record;
begin
  for policy in select policyname from pg_policies where schemaname = 'public' and tablename = 'questdeck_workspaces'
  loop execute format('drop policy %I on public.questdeck_workspaces', policy.policyname); end loop;
  for policy in select policyname from pg_policies where schemaname = 'public' and tablename = 'questdeck_members'
  loop execute format('drop policy %I on public.questdeck_members', policy.policyname); end loop;
  for policy in select policyname from pg_policies where schemaname = 'public' and tablename = 'questdeck_workspace_memberships'
  loop execute format('drop policy %I on public.questdeck_workspace_memberships', policy.policyname); end loop;
end
$$;

alter table public.questdeck_workspace_memberships enable row level security;

create policy questdeck_workspaces_members_read on public.questdeck_workspaces
for select to authenticated using (public.has_questdeck_workspace_access(id));

create policy questdeck_members_shared_workspace_read on public.questdeck_members
for select to authenticated using (
  id = public.questdeck_current_member_id()
  or public.is_questdeck_owner()
  or exists (
    select 1 from public.questdeck_workspace_memberships mine
    join public.questdeck_workspace_memberships theirs on theirs.workspace_id = mine.workspace_id
    where mine.member_id = public.questdeck_current_member_id() and theirs.member_id = questdeck_members.id
  )
);

create policy questdeck_memberships_scoped_read on public.questdeck_workspace_memberships
for select to authenticated using (
  member_id = public.questdeck_current_member_id()
  or public.is_questdeck_owner()
  or public.has_questdeck_workspace_access(workspace_id)
);

do $$
declare policy record;
begin
  for policy in select policyname from pg_policies where schemaname = 'public' and tablename = 'questdeck_role_permissions'
  loop execute format('drop policy %I on public.questdeck_role_permissions', policy.policyname); end loop;
end
$$;
create policy questdeck_roles_members_read on public.questdeck_role_permissions
for select to authenticated using (public.is_questdeck_member());

create policy questdeck_card_editors_update on public.questdeck_cards
for update to authenticated
using (public.can_edit_questdeck_workspace(workspace_id))
with check (public.can_edit_questdeck_workspace(workspace_id));

create policy questdeck_comment_authors_insert on public.questdeck_document_comments
for insert to authenticated
with check (
  public.can_edit_questdeck_workspace(workspace_id)
  and user_id = auth.uid()
  and exists (
    select 1 from public.questdeck_documents document
    where document.id = document_id and document.workspace_id = questdeck_document_comments.workspace_id
  )
);

create policy questdeck_comment_authors_delete on public.questdeck_document_comments
for delete to authenticated
using (public.has_questdeck_workspace_access(workspace_id) and user_id = auth.uid());

grant select on public.questdeck_workspace_memberships to authenticated;
grant usage, select on sequence public.questdeck_workspace_memberships_id_seq to authenticated;

create or replace function public.refresh_questdeck_workspace_member_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.questdeck_workspaces workspace
  set member_count = (
    select count(*) from public.questdeck_workspace_memberships membership
    where membership.workspace_id = workspace.id
  )
  where workspace.id in (coalesce(new.workspace_id, old.workspace_id), coalesce(old.workspace_id, new.workspace_id));
  return coalesce(new, old);
end
$$;

drop trigger if exists questdeck_workspace_member_count_trigger on public.questdeck_workspace_memberships;
create trigger questdeck_workspace_member_count_trigger
after insert or update or delete on public.questdeck_workspace_memberships
for each row execute function public.refresh_questdeck_workspace_member_count();

update public.questdeck_workspaces workspace
set member_count = (
  select count(*) from public.questdeck_workspace_memberships membership
  where membership.workspace_id = workspace.id
);

-- New images use workspace_id/user_id/file. Legacy images belong to the
-- original primary workspace and remain available to its members.
drop policy if exists "Active members can view document images" on storage.objects;
drop policy if exists "Active members can upload document images" on storage.objects;
drop policy if exists "Active members can update document images" on storage.objects;
drop policy if exists "Active members can delete document images" on storage.objects;

create policy "Workspace members can view document images"
on storage.objects for select to authenticated
using (
  bucket_id = 'questdeck-document-images'
  and (
    public.has_questdeck_workspace_access((storage.foldername(name))[1])
    or ((storage.foldername(name))[1] = auth.uid()::text and public.is_questdeck_member())
  )
);

create policy "Workspace members can upload document images"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'questdeck-document-images'
  and public.has_questdeck_workspace_access((storage.foldername(name))[1])
  and (storage.foldername(name))[2] = auth.uid()::text
);

create policy "Workspace members can update own document images"
on storage.objects for update to authenticated
using (
  bucket_id = 'questdeck-document-images'
  and public.has_questdeck_workspace_access((storage.foldername(name))[1])
  and (storage.foldername(name))[2] = auth.uid()::text
)
with check (
  bucket_id = 'questdeck-document-images'
  and public.has_questdeck_workspace_access((storage.foldername(name))[1])
  and (storage.foldername(name))[2] = auth.uid()::text
);

create policy "Workspace members can delete own document images"
on storage.objects for delete to authenticated
using (
  bucket_id = 'questdeck-document-images'
  and public.has_questdeck_workspace_access((storage.foldername(name))[1])
  and (storage.foldername(name))[2] = auth.uid()::text
);
