create table if not exists public.questdeck_activity_events (
  id bigint generated by default as identity primary key,
  actor_name text not null,
  actor_email text not null,
  actor_initials text not null default '',
  action text not null,
  target text not null,
  detail text not null default '',
  project text not null default 'Workspace',
  event_type text not null default 'Workspace',
  tone text not null default 'violet',
  destination text not null default 'overview',
  created_at timestamptz not null default now()
);

create table if not exists public.questdeck_notifications (
  id bigint generated by default as identity primary key,
  recipient_email text not null,
  title text not null,
  detail text not null default '',
  icon text not null default 'Q',
  tone text not null default 'violet',
  destination text not null default 'overview',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists questdeck_activity_events_created_at_idx
  on public.questdeck_activity_events (created_at desc);

create index if not exists questdeck_notifications_recipient_created_idx
  on public.questdeck_notifications (recipient_email, created_at desc);

alter table public.questdeck_activity_events enable row level security;
alter table public.questdeck_notifications enable row level security;

revoke all on public.questdeck_activity_events from anon, authenticated;
revoke all on public.questdeck_notifications from anon, authenticated;

insert into public.questdeck_activity_events (
  actor_name, actor_email, actor_initials, action, target, detail,
  project, event_type, tone, destination
)
select
  'Questdeck', 'system@questdeck.local', 'Q', 'enabled',
  'workspace activity', 'Future workspace changes will appear here.',
  'Workspace', 'Workspace', 'violet', 'activity'
where not exists (select 1 from public.questdeck_activity_events);
