-- Separate workspace owners into independent tenants and keep platform
-- administration content-blind. Platform administrators can provision or
-- suspend owners, but they receive no implicit workspace membership.

create table if not exists public.questdeck_platform_admins (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique,
  email text not null unique,
  display_name text not null default '',
  status text not null default 'Active' check (status in ('Active', 'Suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.questdeck_owner_accounts (
  member_id bigint primary key references public.questdeck_members(id) on delete cascade,
  status text not null default 'Active' check (status in ('Active', 'Suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.questdeck_workspace_role_permissions (
  workspace_id text not null references public.questdeck_workspaces(id) on delete cascade,
  role text not null check (role in ('Owner', 'Admin', 'Team Leader', 'Member', 'Guest')),
  view_projects boolean not null default false,
  edit_cards boolean not null default false,
  manage_members boolean not null default false,
  workspace_settings boolean not null default false,
  billing_security boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (workspace_id, role)
);

alter table public.questdeck_workspace_memberships
  add column if not exists discipline text not null default 'General';

update public.questdeck_workspace_memberships membership
set discipline = coalesce(nullif(member.discipline, ''), 'General')
from public.questdeck_members member
where member.id = membership.member_id
  and membership.discipline = 'General';

insert into public.questdeck_owner_accounts (member_id, status)
select distinct membership.member_id, 'Active'
from public.questdeck_workspace_memberships membership
where membership.role = 'Owner'
on conflict (member_id) do nothing;

insert into public.questdeck_platform_admins (auth_user_id, email, display_name, status)
select member.auth_user_id, lower(member.email), member.name, 'Active'
from public.questdeck_members member
where lower(member.email) = 'polygalbi@gmail.com'
   or lower(member.name) = 'polygalbi'
order by (lower(member.email) = 'polygalbi@gmail.com') desc
limit 1
on conflict (email) do update set
  auth_user_id = coalesce(public.questdeck_platform_admins.auth_user_id, excluded.auth_user_id),
  display_name = excluded.display_name,
  status = 'Active',
  updated_at = now();

insert into public.questdeck_workspace_role_permissions (
  workspace_id, role, view_projects, edit_cards, manage_members, workspace_settings, billing_security
)
select workspace.id, permission.role::text, permission.view_projects, permission.edit_cards,
       permission.manage_members, permission.workspace_settings, permission.billing_security
from public.questdeck_workspaces workspace
cross join public.questdeck_role_permissions permission
on conflict (workspace_id, role) do nothing;

create index if not exists questdeck_owner_accounts_status_idx
  on public.questdeck_owner_accounts (status, member_id);
create index if not exists questdeck_platform_admins_email_idx
  on public.questdeck_platform_admins (lower(email));

alter table public.questdeck_platform_admins enable row level security;
alter table public.questdeck_owner_accounts enable row level security;
alter table public.questdeck_workspace_role_permissions enable row level security;

revoke all on public.questdeck_platform_admins from anon, authenticated;
revoke all on public.questdeck_owner_accounts from anon, authenticated;
grant select on public.questdeck_workspace_role_permissions to authenticated;

create or replace function public.questdeck_current_member_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select member.id
  from public.questdeck_members member
  where lower(member.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    and member.status::text = 'Active'
    and not exists (
      select 1 from public.questdeck_owner_accounts owner_account
      where owner_account.member_id = member.id
        and owner_account.status = 'Suspended'
    )
  limit 1
$$;

create or replace function public.is_questdeck_workspace_owner(target_workspace_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.questdeck_workspace_memberships membership
    where membership.workspace_id = target_workspace_id
      and membership.member_id = public.questdeck_current_member_id()
      and membership.role = 'Owner'
  )
$$;

create or replace function public.can_edit_questdeck_workspace(target_workspace_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.questdeck_workspace_memberships membership
    join public.questdeck_workspace_role_permissions permission
      on permission.workspace_id = membership.workspace_id
     and permission.role = membership.role
    where membership.member_id = public.questdeck_current_member_id()
      and membership.workspace_id = target_workspace_id
      and permission.edit_cards
  )
$$;

revoke all on function public.is_questdeck_workspace_owner(text) from public;
grant execute on function public.is_questdeck_workspace_owner(text) to authenticated;

do $$
declare policy record;
begin
  for policy in select policyname from pg_policies where schemaname = 'public' and tablename = 'questdeck_members'
  loop execute format('drop policy %I on public.questdeck_members', policy.policyname); end loop;
  for policy in select policyname from pg_policies where schemaname = 'public' and tablename = 'questdeck_workspace_memberships'
  loop execute format('drop policy %I on public.questdeck_workspace_memberships', policy.policyname); end loop;
  for policy in select policyname from pg_policies where schemaname = 'public' and tablename = 'questdeck_workspace_role_permissions'
  loop execute format('drop policy %I on public.questdeck_workspace_role_permissions', policy.policyname); end loop;
end
$$;

create policy questdeck_members_shared_workspace_read on public.questdeck_members
for select to authenticated using (
  id = public.questdeck_current_member_id()
  or exists (
    select 1
    from public.questdeck_workspace_memberships mine
    join public.questdeck_workspace_memberships theirs on theirs.workspace_id = mine.workspace_id
    where mine.member_id = public.questdeck_current_member_id()
      and theirs.member_id = questdeck_members.id
  )
);

create policy questdeck_memberships_scoped_read on public.questdeck_workspace_memberships
for select to authenticated using (
  member_id = public.questdeck_current_member_id()
  or public.has_questdeck_workspace_access(workspace_id)
);

create policy questdeck_workspace_roles_scoped_read on public.questdeck_workspace_role_permissions
for select to authenticated using (public.has_questdeck_workspace_access(workspace_id));
