create table if not exists public.questdeck_document_comments (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.questdeck_documents(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  author_email text not null default '',
  author_name text not null default '',
  body text not null check (char_length(body) between 1 and 1200),
  created_at timestamptz not null default now()
);

create index if not exists questdeck_document_comments_document_idx
  on public.questdeck_document_comments (document_id, created_at);

alter table public.questdeck_document_comments enable row level security;

create policy "Workspace members can read document comments"
  on public.questdeck_document_comments for select to authenticated
  using (auth.uid() is not null);

create policy "Workspace members can add document comments"
  on public.questdeck_document_comments for insert to authenticated
  with check (user_id = auth.uid());

create policy "Authors can delete their document comments"
  on public.questdeck_document_comments for delete to authenticated
  using (user_id = auth.uid());
